profile: cover.out
threshold:
  file: 50
  package: 50
  total: 80

local:
  prefix: github.com/joshraphael/go-retroachievements

git:
  token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
  branch: badges

exclude:
  paths:
    - ^examples