name: Smoke

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "**" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approved"
  smoke:
    name: smoke
    needs: authorize
    runs-on: ubuntu-latest
    env:
      RA_API_KEY: ${{ secrets.RA_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
  
      - name: smoke test endpoints
        run: bash ./scripts/smoke.sh